---
apiVersion: v1
kind: Namespace
metadata:
  name: minions

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minions
data:
  MINIO_ROOT_USER: root

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minions
type: Opaque
data:
  
  ##password
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=
---
##headless Service clusterIP: None
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minions
spec:
  clusterIP: None
  selector:
    app: minio
    name: minio-po
  ports:
  - name: data
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090

---
##headful Service
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minions
spec:
  type: ClusterIP
  selector:
    app: minio
    name: minio-po
  ports:
  - name: data 
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minions
spec:
  serviceName: minio-hsvc
  replicas: 3
  selector:
    matchLabels:
      app: minio
      name: minio-po
  volumeClaimTemplates:
  - metadata:
      name: minio-pvc
    spec:
      accessModes: [ ReadWriteOnce ]
      storageClassName: do-block-storage 
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      name: minio-po
      labels:
        app: minio
        name: minio-po
    spec:
      initContainers:
      - name: change-perms
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "chmod 777 /data"
        volumeMounts:
        - name: minio-pvc
          mountPath: /data 
      containers:
      - name: minio-container
        image: bitnami/minio:2023.9.23
        imagePullPolicy: IfNotPresent
        command:
        - minio
        - server
        - --address=:9000
        - --console-address=:9090
        - http://minio-sts-{0...2}.minio-hsvc.minions.svc.cluster.local/data
        envFrom:
        - configMapRef:
            name: minio-cm
        - secretRef:
            name: minio-secret
        ports:
        - name: data
          containerPort: 9000
        - name: console
          containerPort: 9090
        volumeMounts:
        - name: minio-pvc
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          periodSeconds: 60
---
##map to headful services
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: minions
spec:
  ingressClassName: nginx
  rules:
  - host: console-137.184.249.207.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9090
  - host: data-137.184.249.207.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9000

