---
apiVersion: v1
kind: Namespace
metadata: 
  name: minions

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minions
data:
  MINIO_ROOT_USER: root

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minions
type: Opaque
data:
  ##password
    MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=
---
##headless Service clusterIP: None
apiVersion: v1
kind: Service
metadata:
  name: minioapp-hsvc
  namespace: minions
spec:
  clusterIP: None
  selector:
    name: minioapp-po
  ports:
  - name: data
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090

---
##headful Service
apiVersion: v1
kind: Service
metadata:
  name: minioapp-svc
  namespace: minions
spec:
  type: ClusterIP
  selector:
    name: minioapp-po
  ports:
  - name: data
    port: 9000
    targetPort: 9000
  - name: console
    port: 9090
    targetPort: 9090

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minioapp-sts 
  namespace: minions
spec:
  replicas: 3
  serviceName: minioapp-hsvc
  selector:
    matchLabels:
      name: minioapp-po
  volumeClaimTemplates:
  - metadata:
      name: minioapp-pvc
    spec:
      accessModes: [ReadWriteOnce]
      storageClassName: do-block-storage
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      name: minioapp-po
      labels:
        name: minioapp-po
    spec:
      containers:
      - name: minioapp-container
        image: bitnami/minio:2023.9.23
        imagePullPolicy: IfNotPresent
        command:
        - minio
        - server
        - --address=:9000
        - --console-address=:9090
        - http://minio-sts-{0...2}.minioapp-hsvc.minions.svc.cluster.local/data
        envFrom: 
        - configMapRef:
            name: minio-cm
        - secretRef:
            name: minio-secret
        ports:
        - name: data
          containerPort: 9000
        - name: console
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          periodSeconds: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: minions
spec:
  ingressClassName: nginx
  rules:
  - host: 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: minio-svc
            port:
              number: 9090
  - host: data
    http:
      paths:
      - path: /
          pathType: Prefix
          backend:
            service: 
              name: minio-svc
              port:
                number: 9090

