apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  namespace: codeserver
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
  

