apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bgg
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: bgg
  template: 
    metadata: 
      name: bggapp-po
      namespace: bggns
      labels:
        app: bgg
    spec: 
      containers: 
      - name: bggapp-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        envFrom: 
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        ports: 
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
spec:
  type: LoadBalancer
  selector: 
    app: bgg
  ports:
  - port: 8080
    targetPort: 3000

--- 
