apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
    tier: database
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: bgg
      tied: database
      name: bggdb-po
  template: 
    metadata: 
      name: bggdb-po
      labels:
        app: bgg
        tied: database
        name: bggdb-po
    spec: 
      containers: 
      - name: bgg-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 3306
        volumeMounts:
        - name: data-vol
          mountPath: /var/lib/mysql
        - name: bgg-cm
          mountPath: /opt/config
        - name: tmp-vol
          emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
spec:
  ## dont want to expose, therefore use ClusterIP
  type: ClusterIP
  selector: 
    app: bgg
    tied: database
    name: bggdb-po
  ports:
  - port: 3306
    targetPort: 3306


